#!bin/bash
#
echo My First Batch File
#
echo this script name is $0
#
echo The First argument is $1
echo The Second argument is $2
echo The Third argument is $3
#
echo \$ $$ PID of the script
echo \# $# Total number of arguments

